data_source raw:
  type: postgres
  connection:
    host: postgres
    port: 5432
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    schema: raw

data_source public:
  type: postgres
  connection:
    host: postgres
    port: 5432
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    schema: public

data_source recon:
  type: postgres
  connection:
    host: postgres
    port: 5432
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}