services:
  postgres:
    image: postgres:16
    container_name: modelinglab-postgres
    env_file: .env
    ports:
      - "15432:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ops/init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U demo -d modeling_lab" ]
      interval: 5s
      timeout: 5s
      retries: 20

  dagster-web:
    build:
      context: .
      dockerfile: orchestration/dagster/Dockerfile
    container_name: modelinglab-dagster-web
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    ports:
      - "3002:3000"
      - "8099:8099"
    volumes:
      - dagster_home:/orchestration/dagster/dagster_home
      - ./:/app
    command: [ "dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-m", "orchestration.dagster.dagster_project" ]

  dagster-daemon:
    build:
      context: .
      dockerfile: orchestration/dagster/Dockerfile
    container_name: modelinglab-dagster-daemon
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    volumes:
      - dagster_home:/opt/dagster/dagster_home
      - ./:/app
    command: [ "dagster-daemon", "run" ]

  metabase:
    image: metabase/metabase:latest
    container_name: modelinglab-metabase
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      - MB_DB_TYPE=${MB_DB_TYPE}
      - MB_DB_DBNAME=${MB_DB_DBNAME}
      - MB_DB_PORT=${MB_DB_PORT}
      - MB_DB_USER=${MB_DB_USER}
      - MB_DB_PASS=${MB_DB_PASS}
      - MB_DB_HOST=${MB_DB_HOST}
    env_file: .env

volumes:
  pgdata:
  dagster_home:
  metabase_data:
