CREATE DATABASE dagster_meta;

\connect modeling_lab;

CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
--CREATE SCHEMA IF NOT EXISTS core_3nf;
--CREATE SCHEMA IF NOT EXISTS dv;
--CREATE SCHEMA IF NOT EXISTS marts;
--CREATE SCHEMA IF NOT EXISTS ops;